spring:
  datasource:
    username: IpMan
    password: Cuit135..*
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://148.70.213.176:3306/patent?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC

mybatis:
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    org.springframework.web: info
    com.github.binarywang.demo.wx.pay: debug
    com.github.binarywang.wxpay: debug

path:
  log: C:/Users/Ftu/Desktop/test/backLog

server:
  ip: 148.70.213.176
  useLessMem: true
